# Below is the configuration of the CI build
env_defaults: &env_defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16

version: 2.1
commands:
  unit_test:
    description: Run a suite of unit tests for a contract
    parameters:
      test:
        type: string
        default: ''
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: TRUFFLE_TEST=<< parameters.test >> npm run test:gas
      - run: npx codechecks

jobs:
  prepare:
    <<: *env_defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - 'v1.5-dependencies-{{ checksum "package-lock.json" }}'
            - v1.5-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1.5-dependencies-{{ checksum "package-lock.json" }}'
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint

  unit_DelegateApprovals:
    <<: *env_defaults
    steps:
      - unit_test:
        test: test/DelegateApprovals.js

  unit_Depot:
    <<: *env_defaults
    steps:
      - unit_test:
        test: test/Depot.js

  int:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:int

workflows:
  version: 2
  dev:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      # Here all the unit tests in JS are split out to parallelize for speed
      - unit_DelegateApprovals:
          requires:
            - prepare
      - unit_Depot:
          requires:
            - prepare
      - int:
          requires:
            - prepare
