# Below is the configuration of the CI build
env_defaults: &env_defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16

version: 2.1
commands:
  unit_test:
    description: Run a suite of unit tests for a contract
    parameters:
      test:
        type: string
        default: '*'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'TRUFFLE_TEST=test/contracts/<< parameters.test >> npm run test:gas'
      - run: npx codechecks
jobs:
  prepare:
    <<: *env_defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - 'v2-dependencies-{{ checksum "package-lock.json" }}'
            - v2-dependencies-
      - run: npm install
      - run: npx truffle compile
      - save_cache:
          paths:
            - node_modules
          key: 'v2-dependencies-{{ checksum "package-lock.json" }}'
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            # add compiled contracts to persisted workspace
            # (note not currentlyw orking due to:
            # https://github.com/trufflesuite/truffle/issues/2239#issuecomment-552041859)
            - build

  lint:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint

  test-contracts:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:gas
      - run: npx codechecks

  test-contracts-synthetix:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - unit_test:
        test: Synthetix.js

  test-publish:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:publish
      - run: cat test/publish/test.log

  test-kovan:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:testnet --  --yes --network kovan

  test-rinkeby:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:testnet --  --yes --network rinkeby

  test-ropsten:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:testnet --  --yes --network ropsten

workflows:
  version: 2
  dev:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test-contracts:
          requires:
            - prepare
      - test-contracts-synthetix:
          requires:
            - prepare
      - test-publish:
          requires:
            - prepare
      - test-kovan:
          requires:
            - prepare
          filters:
            branches:
              only: alpha
      - test-rinkeby:
          requires:
            - prepare
          filters:
            branches:
              only: beta
      - test-ropsten:
          requires:
            - prepare
          filters:
            branches:
              only: release-candidate
